name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  island-scene:
    runs-on: macos-latest

    - uses: actions/checkout@v3

    - name: Build pbrt_proto_converter
      run: bazel build -c opt //tools:pbrt_proto_converter

    - name: Download island scene
      run: curl -O https://wdas-datasets-disneyanimation-com.s3-us-west-2.amazonaws.com/moanaislandscene/island-pbrt-v1.1.tgz

    - name: Extract island scene
      run: tar -xvf island-pbrt-v1.1.tgz && rm island-pbrt-v1.1.tgz

    - name: Convert island scene
      run: bazel run -c opt //tools:pbrt_proto_converter -- --pbrt_version=3 --recursive $GITHUB_WORKSPACE/island/pbrt/island.pbrt

  build-linux-gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: debug build
      run: bazel build ...

    - name: debug tests
      run: bazel test ...

    - name: optimized build
      run: bazel build -c opt ...

    - name: optimized tests
      run: bazel test -c opt ...

  build-linux-clang:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]

    steps:
    - uses: actions/checkout@v3

    - name: debug build
      run: bazel build ... --repo_env=cc=clang

    - name: debug tests
      run: bazel test ... --repo_env=cc=clang

    - name: optimized build
      run: bazel build -c opt ... --repo_env=cc=clang

    - name: optimized tests
      run: bazel test -c opt ... --repo_env=cc=clang

  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2022]

    steps:
    - uses: actions/checkout@v3

    - name: debug build
      run: bazel --output_base=C:\b build ...

    - name: debug tests
      run: bazel --output_base=C:\b test ...

    - name: optimized build
      run: bazel --output_base=C:\b build -c opt

    - name: optimized tests
      run: bazel --output_base=C:\b test -c opt ...


  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-14]

    steps:
    - uses: actions/checkout@v3

    - name: debug build
      run: bazel build ...

    - name: debug tests
      run: bazel test ...

    - name: optimized build
      run: bazel build -c opt

    - name: optimized tests
      run: bazel test -c opt ...
