name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 1024
        remove-android: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - name: Download island scene
      run: wget https://wdas-datasets-disneyanimation-com.s3-us-west-2.amazonaws.com/moanaislandscene/island-pbrt-v1.1.tgz

    - name: Extract island scene
      run: tar -xvf island-pbrt-v1.1.tgz && rm island-pbrt-v1.1.tgz

    - uses: actions/checkout@v3

    - name: debug build (gcc)
      run: bazel build ...

    - name: debug tests (gcc)
      run: bazel test ...

    - name: optimized build (gcc)
      run: bazel build -c opt ...

    - name: optimized tests (gcc)
      run: bazel test -c opt ...

    - name: debug build (clang)
      run: bazel build ... --repo_env=cc=clang

    - name: debug tests (clang)
      run: bazel test ... --repo_env=cc=clang

    - name: optimized build (clang)
      run: bazel build -c opt ... --repo_env=cc=clang

    - name: optimized tests (clang)
      run: bazel test -c opt ... --repo_env=cc=clang
